language: android
dist: focal
os: linux
jdk: oraclejdk8

env:
  global:
    - ANDROID_API_LEVEL=30
    - ANDROID_BUILD_TOOLS_VERSION=30.0.2

git:
  depth: false

addons:
  sonarcloud:
    organization: "khongi"
    token:
      secure: "Py20jtyzzeL/bf6pqnabKSHQ6KwtIQnv8nu8Tspax1jm+tGmMSu6FDVxa59syZmFcBxtJYa2usKGVHXQwQBVKbF5VCt/z0noMdy+/3rmSO4SgQt7dpObFRQcJeQdSfmM8X/OHDFYqPaHPa4Wytbw4e+MYb2Bi/raiL3fxJLQ1kJoW/me53myOlODGms0zgsnzf/YjBjTvljpGyqArsNjHaHuD8zmOFtbMqErYokQv5GgDKyR6ar8UaMxMoC0/X2tSLjYBDY+90WeW/PX6KuzaGNfcSHiX9jTJZgbyasj42JC+f9kW1I+tz9V1m1ubL35wxb5UsGQsHe4TfLq1w2wRYTgOYJEzP1qI7e/tzCDypU3VZ9ccjzzGTjvoNNGW7Sc7ML1Pwm0KpNivEEtgrNiNsEx04DLEjovd5UJDukFJyh7IRcFR9x0exTSbN9GCj1ihDiey0khWqkFjl31yytn41AMUHm1bTtLKntmqdWjTgBJfQHP7q3hI3uBiB5KxpO3uVDWLzHy9jVKQvl5oADMIMAR40NWJdJebCzqYsCjkvM+nviQQotMaOwszsHavqEeNUMitCOa2iT1TEhINk1zBwHCLduGTvvCfUxxysWJWzzm8mVTaCdeisQV1E2wB5G5hSdgESkxUhrgKjJ5bDpevAHB8Oz7y3PLmGQwj9YTvs4="

android:
  components:
    - tools
    - platform-tools
    - tools
    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

  licenses:
  # White list all the licenses.
    - '.+'

before_install:
  - PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/tools/bin:${ANDROID_HOME}/platform-tools
  - export ANDROID_SDK_ROOT=${ANDROID_HOME}
  - touch $HOME/.android/repositories.cfg
  - yes | sdkmanager "platforms;android-$ANDROID_API_LEVEL"
  - yes | sdkmanager "build-tools;$ANDROID_BUILD_TOOLS_VERSION"

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

script:
  - ./gradlew assembleDebug testDebugUnitTest lintDebug
  - export JAVA_HOME=$HOME/oraclejdk11
  - chmod +x $TRAVIS_BUILD_DIR/ci/install-jdk.sh
  - $TRAVIS_BUILD_DIR/ci/install-jdk.sh --target $JAVA_HOME --workspace "/home/travis/.cache/install-jdk" --feature "11" --license "BCL"
  - sonar-scanner

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
    - $HOME/.cache

notifications:
  email: false
  slack:
    secure: IXegsWO3Wyy3tqXPA7mczpUE5fS4yQ5Z4L3GBjm3GuAYljzql+5GqvcTFNFmaoyD4wvHCqV7uHGmk+LBG15jTHoJGN2D+dSSPGc7qCS7NzEQFcRZt/LRG+CK/VZGmlzyEg2P6yTiKUVO8XfAIS9prlzRgGopoYxaqGWFhpy6m7l792lAcmAueUyJVtdi3IiPy+0XmKAv64ldOt3Bg9aLzSmd/8vcYZqzGxnWIosKTmPEdJvbBiEOpFZZjGaOJpY69zhe8ZJjf9gHvLxAZVUsmQAk8ii3T0AuJzug/pOnfU7birpbXzD8WK378/Wt7LDsNbEUgn3kKnuFy/Fj76AXcJzcWzqQbIB9XfmzVyxqvj88xcgdW8XoH+czaqLZj4xD2FGwq4xrq2yBy1KggqgRDBeBegvZvAi8lWJjSkTWynqwaiIr2lWCTy+Z2PwUiMlZFOETUjxKlKZzxYTt0e39SLbLbBzceqVjIpNHpW6liGJR2g/NRd4El8ytdvFDUTDAlMh2Ztr5tMdVlSDIGYXG7buv4swngWvQ+u/EtNnzlRnWRPsAxnfvzanAnyPDp2JqRJ58W9Olq5nzQmrYuaABdMpeqsg+wyPn4cnagZ+YEDuF8mckLrh7qiJuV7EhRpThSRPoAFkrNugrJddDL7gETuYZOVdlXdWpANh+ukjTou8=
